# Generated by Django 5.0.3 on 2024-03-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_post_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
    ]
